JXBasicAuth: admin:{SHA}6f5R+U6tq/VNvy+71XGIuavuQ24=
chartmuseum:
  secret:
    BASIC_AUTH_USER: admin
    BASIC_AUTH_PASS: mysecret
grafana:
  server:
    adminUser: admin
    adminPassword: mysecret
jenkins:
  Master:
    AdminPassword: mysecret
